"""Category taxonomy bootstrap and resolution helpers."""

import logging
import uuid

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.db.models import Category

logger = logging.getLogger(__name__)

# Keep this compact and opinionated for deterministic categorization.
DEFAULT_CATEGORY_TREE: dict[str, list[str]] = {
    "Food": [
        "Fresh Produce",
        "Meat",
        "Poultry",
        "Fish & Seafood",
        "Dairy",
        "Eggs",
        "Bakery",
        "Rice & Grains",
        "Pasta & Noodles",
        "Canned & Jarred",
        "Frozen Food",
        "Snacks",
        "Beverages",
        "Breakfast & Cereals",
        "Sauces & Condiments",
        "Cooking Essentials",
        "International Foods",
        "Ready-to-Eat & Prepared",
        "Sweets & Desserts",
        "Meal Kits",
    ],
    "Fresh Produce": [
        "Fruit",
        "Vegetables",
        "Herbs",
        "Salad Mixes",
        "Pre-cut Produce",
        "Mushrooms",
        "Garlic & Onions",
        "Citrus",
        "Berries",
        "Tropical Fruit",
        "Stone Fruit",
        "Leafy Greens",
        "Root Vegetables",
        "Cruciferous Vegetables",
        "Tomatoes & Peppers",
        "Seasonal Produce",
    ],
    "Meat": [
        "Beef",
        "Pork",
        "Lamb",
        "Game",
        "Deli Meats",
        "Bacon & Sausages",
        "Marinated & Seasoned Meats",
        "Ground Meat",
        "Steaks & Roasts",
        "Ribs & Chops",
    ],
    "Poultry": [
        "Chicken",
        "Turkey",
        "Duck",
        "Quail",
        "Ground Poultry",
        "Breasts & Fillets",
        "Thighs & Drumsticks",
        "Whole Birds",
        "Wings",
        "Deli Poultry",
    ],
    "Fish & Seafood": [
        "Fresh Fish",
        "Frozen Fish",
        "Shellfish",
        "Smoked Fish",
        "Canned Fish & Seafood",
        "Sushi-Grade",
        "Fish Fillets",
        "Seafood Mixes",
    ],
    "Dairy": [
        "Milk",
        "Yogurt",
        "Cheese",
        "Butter & Margarine",
        "Cream",
        "Plant-Based Alternatives",
        "Kefir",
        "Dessert Dairy",
    ],
    "Milk": [
        "Whole Milk",
        "Semi-Skimmed Milk",
        "Skimmed Milk",
        "Lactose-Free Milk",
        "A2 Milk",
        "Flavored Milk",
        "UHT & Shelf-Stable Milk",
        "Fresh Milk",
    ],
    "Plant-Based Alternatives": [
        "Almond Milk",
        "Oat Milk",
        "Soy Milk",
        "Coconut Milk (Drink)",
        "Rice Milk",
        "Pea Milk",
        "Plant-Based Yogurt",
        "Plant-Based Cheese",
        "Plant-Based Creamers",
        "Barista Milks",
    ],
    "Eggs": [
        "Chicken Eggs",
        "Free-Range Eggs",
        "Organic Eggs",
        "Omega-3 Eggs",
        "Quail Eggs",
        "Liquid Egg Whites",
        "Boiled & Ready Eggs",
    ],
    "Bakery": [
        "Bread",
        "Buns & Rolls",
        "Tortillas & Flatbreads",
        "Pastries & Croissants",
        "Cakes & Pies",
        "Cookies & Biscuits",
        "Bakery Gluten-Free",
        "Artisanal & Sourdough",
        "Burger & Hot Dog Buns",
        "Breakfast Bakery",
    ],
    "Rice & Grains": [
        "Rice",
        "Quinoa & Ancient Grains",
        "Couscous & Bulgur",
        "Barley & Farro",
        "Polenta & Cornmeal",
        "Meal Prep Grain Packs",
        "Microwave Pouches",
    ],
    "Rice": [
        "Long Grain",
        "Basmati",
        "Jasmine",
        "Medium Grain",
        "Short Grain & Sushi",
        "Brown Rice",
        "Wild Rice",
        "Arborio & Risotto",
        "Parboiled & Converted",
        "Rice Blends",
        "Instant Rice",
    ],
    "Pasta & Noodles": [
        "Dry Pasta",
        "Fresh & Refrigerated Pasta",
        "Whole Wheat & High-Protein Pasta",
        "Gluten-Free Pasta",
        "Asian Noodles",
        "Gnocchi",
        "Stuffed Pasta",
        "Instant Noodles & Ramen",
    ],
    "Canned & Jarred": [
        "Tomatoes & Sauces",
        "Beans & Legumes (Canned)",
        "Vegetables (Canned)",
        "Fruit (Canned)",
        "Tuna & Canned Fish",
        "Soups & Broths (Canned)",
        "Coconut Milk (Canned)",
        "Ready Meals (Canned)",
        "Olives & Pickles",
        "Jarred Peppers & Artichokes",
    ],
    "Frozen Food": [
        "Frozen Vegetables",
        "Frozen Fruit",
        "Frozen Pizza",
        "Frozen Meals",
        "Frozen Meat & Poultry",
        "Frozen Fish & Seafood",
        "Ice Cream & Novelties",
        "Frozen Bread & Pastry",
        "Frozen Potatoes",
        "Frozen Breakfast",
        "Frozen Dumplings & Gyoza",
    ],
    "Snacks": [
        "Chips & Crisps",
        "Nuts & Seeds",
        "Popcorn",
        "Crackers",
        "Jerky & Meat Snacks",
        "Protein Bars",
        "Granola & Snack Bars",
        "Dried Fruit",
        "Rice Cakes",
        "Savory Snacks",
        "Healthy Snacks",
        "Party Mixes",
    ],
    "Beverages": [
        "Water",
        "Soft Drinks",
        "Juice",
        "Iced Tea & Tea Drinks",
        "Coffee Drinks",
        "Energy & Sports Drinks",
        "Milk Drinks",
        "Plant-Based Drinks",
        "Mixers",
        "Kombucha & Fermented Drinks",
        "Non-Alcoholic Beers & Wines",
        "Powdered & Concentrate Drinks",
    ],
    "Water": [
        "Still Water",
        "Sparkling Water",
        "Mineral Water",
        "Flavored Water",
        "Electrolyte Water",
        "Large Jugs & Dispensers",
        "Water Filters & Cartridges",
    ],
    "Coffee": [
        "Whole Bean",
        "Ground Coffee",
        "Pods & Capsules",
        "Instant Coffee",
        "Coffee Beans Specialty",
        "Decaf",
        "Cold Brew",
        "Coffee Filters & Accessories",
        "Coffee Syrups",
    ],
    "Tea": [
        "Black Tea",
        "Green Tea",
        "Herbal Tea",
        "Oolong & White",
        "Chai",
        "Matcha",
        "Iced Tea Mix",
        "Loose Leaf",
        "Tea Accessories",
    ],
    "Breakfast & Cereals": [
        "Cold Cereal",
        "Oatmeal & Porridge",
        "Granola & Muesli",
        "Pancake & Waffle Mix",
        "Syrups & Toppings",
        "Breakfast Bars",
        "Nut Butters",
        "Jam & Spreads",
        "Honey",
        "Cacao & Cocoa Powder",
    ],
    "Sauces & Condiments": [
        "Tomato Sauces & Pasta Sauce",
        "Pesto & Alfredo",
        "Soy Sauce & Teriyaki",
        "Hot Sauce & Sriracha",
        "BBQ Sauce",
        "Ketchup & Mustard",
        "Mayonnaise & Aioli",
        "Salad Dressings",
        "Vinegar",
        "Oils",
        "Pickles & Relish",
        "Chutneys & Relishes",
        "Salsas & Dips",
        "Tahini & Middle Eastern",
    ],
    "Cooking Essentials": [
        "Flour & Baking",
        "Sugar & Sweeteners",
        "Baking Mixes",
        "Yeast & Leaveners",
        "Spices & Seasonings",
        "Herbs & Rubs",
        "Stock & Broth",
        "Ghee & Specialty Fats",
        "Salt & Pepper",
        "Breadcrumbs & Coatings",
        "Gelatin & Thickeners",
    ],
    "International Foods": [
        "Mexican & Latin",
        "Asian",
        "Indian",
        "Mediterranean & Middle Eastern",
        "Italian",
        "American BBQ & Southern",
        "European",
        "African",
    ],
    "Ready-to-Eat & Prepared": [
        "Rotisserie & Ready Meats",
        "Prepared Salads",
        "Fresh Soups",
        "Meal Prep Bowls",
        "Chilled Pasta & Sauces",
        "Sushi & Poke",
        "Dips & Hummus",
        "Cut Fruit & Veg",
    ],
    "Sweets & Desserts": [
        "Chocolate",
        "Candy",
        "Pudding & Custard",
        "Gelatin Desserts",
        "Baking Chocolate & Chips",
        "Dessert Toppings",
        "Marshmallows",
        "Seasonal Sweets",
    ],
    "Meal Kits": [
        "2-Serving Kits",
        "Family-Size Kits",
        "Stir-Fry Kits",
        "Taco & Fajita Kits",
        "Salad Kits",
        "Pizza Kits",
        "Curry Kits",
    ],
    "Household": [
        "Cleaning Supplies",
        "Paper Products",
        "Laundry",
        "Kitchen Supplies",
        "Home Organization",
        "Trash & Recycling",
        "Batteries & Light Bulbs",
        "Air Care",
        "Pest Control",
        "Tools & Repairs",
        "Outdoor & BBQ",
        "Toilet Paper & Tissues",
    ],
    "Cleaning Supplies": [
        "Multi-Surface Cleaners",
        "Bathroom Cleaners",
        "Kitchen Cleaners",
        "Floor Cleaners",
        "Glass & Window Cleaners",
        "Disinfectants",
        "Degreasers",
        "Dishwashing Liquid",
        "Dishwasher Detergent",
        "Sponges & Scourers",
        "Cleaning Cloths & Paper",
        "Mops & Brooms",
        "Buckets & Brushes",
        "Descalers & Limescale",
        "Drain Cleaners",
        "Oven & Grill Cleaners",
        "Stainless Steel Care",
        "Wood & Furniture Care",
        "Air Fresheners",
    ],
    "Paper Products": [
        "Toilet Paper",
        "Paper Towels",
        "Facial Tissues",
        "Napkins",
        "Paper Plates & Cups",
        "Food Wraps & Foil",
        "Baking Paper & Parchment",
        "Freezer & Storage Bags",
    ],
    "Laundry": [
        "Laundry Detergent",
        "Fabric Softener",
        "Stain Removers",
        "Laundry Additives & Boosters",
        "Laundry Pods & Sheets",
        "Wool Dryer Balls",
        "Ironing & Starch",
        "Laundry Baskets & Hampers",
        "Clotheslines & Pins",
    ],
    "Kitchen Supplies": [
        "Trash Bags",
        "Food Storage & Containers",
        "Meal Prep Containers",
        "Food Wraps & Foil",
        "Zip Bags",
        "Reusable Bags",
        "Single-Use Tableware",
        "Sponges & Scrubbers",
        "Gloves",
        "Cutting Boards",
        "Utensils & Gadgets",
        "Bakeware",
        "Cookware",
        "Thermometers & Timers",
        "Water Bottles & Jugs",
        "Coffee & Tea Equipment",
    ],
    "Home Organization": [
        "Storage Bins & Baskets",
        "Closet Organizers",
        "Shoe Racks",
        "Hooks & Hangers",
        "Drawer Dividers",
        "Shelving",
        "Labels",
        "Cable Management",
        "Desk Organizers",
    ],
    "Trash & Recycling": [
        "Trash Bags",
        "Recycling Bags",
        "Compost Bags",
        "Bins & Caddies",
        "Compost Bins",
        "Trash Cans",
        "Bin Liners",
    ],
    "Batteries & Light Bulbs": [
        "AA Batteries",
        "AAA Batteries",
        "9V & Button Cells",
        "Rechargeable Batteries",
        "Chargers",
        "LED Bulbs",
        "Smart Bulbs",
        "Specialty Bulbs",
        "Flashlights",
        "Night Lights",
    ],
    "Air Care": [
        "Air Fresheners",
        "Plug-ins & Refills",
        "Scented Candles",
        "Reed Diffusers",
        "Essential Oils",
        "Dehumidifiers & Moisture Absorbers",
        "HEPA & Air Filters",
    ],
    "Pest Control": [
        "Insect Sprays",
        "Ant & Roach Baits",
        "Rodent Control",
        "Fly Traps",
        "Mosquito Repellents",
        "Moth Protection",
    ],
    "Tools & Repairs": [
        "Basic Tools",
        "Adhesives & Tapes",
        "Superglue & Epoxy",
        "Batteries & Power",
        "Picture Hanging",
        "Hooks & Command Strips",
        "Felt Pads & Furniture Sliders",
        "Sealants & Caulk",
    ],
    "Outdoor & BBQ": [
        "Charcoal & Wood Chips",
        "Lighters & Fire Starters",
        "BBQ Tools",
        "Grill Cleaners",
        "Coolers & Ice Packs",
        "Patio Care",
        "Garden Gloves",
    ],
    "Personal Care": [
        "Hygiene",
        "Beauty",
        "Health & Medicine",
        "Shaving & Beard",
        "Hair Care",
        "Oral Care",
        "Bath & Body",
        "Deodorant",
        "Sun Care",
        "Sexual Wellness",
        "Men's Grooming",
        "Foot Care",
        "First Aid",
    ],
    "Hygiene": [
        "Body Wash & Soap",
        "Hand Soap",
        "Hand Sanitizer",
        "Deodorant & Antiperspirant",
        "Wet Wipes",
        "Tissues",
        "Cotton & Swabs",
        "Feminine Care",
        "Toilet Paper",
        "Bidet & Hygiene Accessories",
    ],
    "Beauty": [
        "Face Care",
        "Body Care",
        "Makeup",
        "Fragrance",
        "Nail Care",
        "Tools & Accessories",
        "Men's Skincare",
    ],
    "Face Care": [
        "Cleanser",
        "Toner",
        "Serum",
        "Moisturizer",
        "Sunscreen (Face)",
        "Eye Care",
        "Lip Care",
        "Acne Treatments",
        "Face Masks",
        "Cleansing Balms & Oils",
    ],
    "Hair Care": [
        "Shampoo",
        "Conditioner",
        "Hair Treatments & Masks",
        "Styling Products",
        "Hair Tools & Brushes",
        "Hair Color",
        "Dry Shampoo",
        "Anti-Dandruff",
        "Beard & Moustache Care",
    ],
    "Oral Care": [
        "Toothpaste",
        "Toothbrushes",
        "Floss & Picks",
        "Mouthwash",
        "Whitening",
        "Interdental & Water Flossers",
        "Dental Repairs & Wax",
    ],
    "Bath & Body": [
        "Bar Soap",
        "Body Wash",
        "Bath Salts & Soaks",
        "Body Lotion",
        "Hand Cream",
        "Foot Cream",
        "Body Scrubs",
        "Massage Oils",
    ],
    "Deodorant": [
        "Stick",
        "Roll-On",
        "Spray",
        "Cream",
        "Natural & Aluminum-Free",
        "Clinical Strength",
    ],
    "Shaving & Beard": [
        "Razors",
        "Razor Blades",
        "Shaving Cream & Gel",
        "Aftershave",
        "Beard Oil & Balm",
        "Trimmers & Accessories",
        "Shaving Brushes & Bowls",
        "Pre-Shave Oils",
    ],
    "Sun Care": [
        "Face Sunscreen",
        "Body Sunscreen",
        "After Sun",
        "Self Tanners",
        "SPF Lip Care",
    ],
    "Men's Grooming": [
        "Face Wash",
        "Moisturizer",
        "Beard Care",
        "Shaving",
        "Hair Styling",
        "Fragrance",
        "Eye Rollers",
    ],
    "Health & Medicine": [
        "Pain Relief",
        "Cold & Flu",
        "Allergy",
        "Digestive Health",
        "Vitamins & Supplements",
        "Sleep Aids",
        "First Aid",
        "Sports Supports",
        "Eye & Ear Care",
        "Stop Smoking Aids",
        "Thermometers",
    ],
    "First Aid": [
        "Bandages & Gauze",
        "Antiseptics",
        "Ointments",
        "Ice Packs & Heat Packs",
        "Tape & Wraps",
        "Gloves",
        "First Aid Kits",
    ],
    "Baby & Pet": [
        "Baby Care",
        "Pet Food",
        "Pet Care",
    ],
    "Baby Care": [
        "Diapers",
        "Wipes",
        "Baby Bath & Shampoo",
        "Baby Lotion & Creams",
        "Baby Medicine",
        "Baby Feeding",
        "Baby Accessories",
    ],
    "Pet Food": [
        "Dog Food",
        "Cat Food",
        "Small Animal Food",
        "Bird Food",
        "Fish Food",
        "Pet Treats",
    ],
    "Pet Care": [
        "Litter & Waste Bags",
        "Pet Grooming",
        "Flea & Tick",
        "Pet Health",
        "Leashes & Collars",
        "Bowls & Accessories",
        "Pet Beds & Crates",
    ],
    "Other": [
        "Uncategorized",
        "Stationery & Office",
        "Electronics Small",
        "Clothing Basics",
        "Travel & Commute",
        "Hobbies & Games",
        "Seasonal & Party",
    ],
    "Stationery & Office": [
        "Notebooks",
        "Pens & Pencils",
        "Markers & Highlighters",
        "Sticky Notes",
        "Printer Paper",
        "Envelopes & Mailers",
        "Tape & Glue",
        "Scissors & Cutters",
        "Desk Accessories",
    ],
    "Electronics Small": [
        "Phone Chargers & Cables",
        "Power Banks",
        "Headphones & Earbuds",
        "Smart Plugs",
        "USB Hubs & Adapters",
        "Memory Cards",
        "Batteries",
        "Flash Drives",
    ],
    "Clothing Basics": [
        "Socks",
        "Underwear",
        "T-Shirts",
        "Sleepwear",
        "Loungewear",
        "Rain Gear",
        "Workout Gear",
    ],
    "Travel & Commute": [
        "Transit Cards & Top-Ups",
        "Travel-Size Toiletries",
        "Neck Pillows & Masks",
        "Refillable Bottles",
        "Bike Accessories",
        "Umbrellas",
    ],
    "Hobbies & Games": [
        "Board Games & Cards",
        "Puzzles",
        "Art Supplies",
        "Books & Magazines",
        "Music Accessories",
        "Sports Balls & Pumps",
        "Camping Basics",
    ],
    "Seasonal & Party": [
        "Party Supplies",
        "Decorations",
        "Gift Wrap & Bags",
        "Candles",
        "Picnic & Disposable Tableware",
        "Holiday Themes",
    ],
    "Uncategorized": [],
}


def _pretty_name(node_name: str) -> str:
    mapping = {
        "PersonalCare": "Personal Care",
        "BabyAndPet": "Baby & Pet",
        "FishAndSeafood": "Fish & Seafood",
        "RiceAndGrains": "Rice & Grains",
        "PastaAndNoodles": "Pasta & Noodles",
        "FrozenFood": "Frozen Food",
        "SaucesAndCondiments": "Sauces & Condiments",
        "CleaningSupplies": "Cleaning Supplies",
        "PaperProducts": "Paper Products",
        "KitchenSupplies": "Kitchen Supplies",
        "HealthAndMedicine": "Health & Medicine",
        "BabyCare": "Baby Care",
        "PetFood": "Pet Food",
        "PetCare": "Pet Care",
    }
    return mapping.get(node_name, node_name)


async def ensure_default_categories(session: AsyncSession) -> None:
    """Ensure baseline English taxonomy exists."""
    stmt = select(Category)
    result = await session.execute(stmt)
    existing_categories = list(result.scalars().all())

    by_name: dict[str, Category] = {c.name.lower(): c for c in existing_categories}

    for root_name, children in DEFAULT_CATEGORY_TREE.items():
        root_pretty = _pretty_name(root_name)
        root = by_name.get(root_pretty.lower())
        if root is None:
            root = Category(id=uuid.uuid4(), name=root_pretty, parent_id=None)
            session.add(root)
            await session.flush()
            by_name[root_pretty.lower()] = root

        for child_name in children:
            child_pretty = _pretty_name(child_name)
            child = by_name.get(child_pretty.lower())
            if child is None:
                child = Category(id=uuid.uuid4(), name=child_pretty, parent_id=root.id)
                session.add(child)
                await session.flush()
                by_name[child_pretty.lower()] = child
            elif child.parent_id is None:
                child.parent_id = root.id

    logger.info("Category taxonomy bootstrap completed.")


async def resolve_or_create_category_path(
    session: AsyncSession,
    category_path_en: str | None,
) -> uuid.UUID | None:
    """Resolve a category path like 'Food > Poultry' and return leaf category id."""
    if not category_path_en:
        return None

    parts = [
        _pretty_name(part.strip())
        for part in category_path_en.split(">")
        if part.strip()
    ]
    if not parts:
        return None

    parent_id: uuid.UUID | None = None
    current: Category | None = None

    for part in parts:
        stmt = select(Category).where(
            Category.name.ilike(part),
            Category.parent_id == parent_id,
        )
        result = await session.execute(stmt)
        current = result.scalar_one_or_none()
        if current is None:
            current = Category(id=uuid.uuid4(), name=part, parent_id=parent_id)
            session.add(current)
            await session.flush()
        parent_id = current.id

    return current.id if current else None
